# Generated by Django 5.1.2 on 2024-10-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
