# Generated by Django 5.1.2 on 2024-10-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0002_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
