# Generated by Django 5.1.2 on 2024-10-31 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0003_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tests', to='otosapp.category'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='otosapp.test'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Is this the correct answer?'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='otosapp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='otosapp.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Taken'),
        ),
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.FloatField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.ForeignKey(limit_choices_to={'userprofile__role__role_name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
