# Generated by Django 5.1.2 on 2025-08-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0006_alter_choice_choice_text_alter_question_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
