# Generated by Django 5.1.2 on 2025-08-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0007_alter_choice_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit in minutes (default: 60 minutes)'),
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test End Time'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Is Submitted'),
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Test Start Time'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=60, verbose_name='Time Limit (minutes)'),
        ),
    ]
