# Generated by Django 5.1.2 on 2025-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0008_category_time_limit_test_end_time_test_is_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scoring_method',
            field=models.CharField(choices=[('default', 'Default (100/jumlah soal)'), ('custom', 'Custom (nilai per soal)'), ('utbk', 'UTBK (difficulty-based)')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='custom_weight',
            field=models.FloatField(default=0, help_text='Custom weight for scoring (0-100)'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_coefficient',
            field=models.FloatField(default=1.0, help_text='UTBK difficulty coefficient (auto-calculated)'),
        ),
    ]
