# Generated by Django 5.1.2 on 2025-08-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0009_category_scoring_method_question_custom_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='passing_score',
            field=models.FloatField(default=75.0, help_text='Minimum score required to pass (0-100)'),
        ),
    ]
