# Generated by Django 5.1.2 on 2025-08-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0012_messagethread_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Paket')),
                ('package_type', models.CharField(choices=[('basic', 'Paket Dasar'), ('premium', 'Paket Premium'), ('pro', 'Paket Pro'), ('ultimate', 'Paket Ultimate')], max_length=20, verbose_name='Tipe Paket')),
                ('description', models.TextField(verbose_name='Deskripsi Paket')),
                ('features', models.TextField(help_text='Fitur-fitur yang tersedia (satu per baris)', verbose_name='Fitur')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('duration_days', models.IntegerField(verbose_name='Durasi (hari)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Paket Unggulan')),
            ],
            options={
                'verbose_name': 'Paket Berlangganan',
                'verbose_name_plural': 'Paket Berlangganan',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(upload_to='payment_proofs/', verbose_name='Bukti Pembayaran')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Metode Pembayaran')),
                ('payment_date', models.DateTimeField(verbose_name='Tanggal Pembayaran')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Bayar')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi oleh')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otosapp.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Bukti Pembayaran',
                'verbose_name_plural': 'Bukti Pembayaran',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_downgrade_processed', models.BooleanField(default=False, help_text='Apakah downgrade otomatis sudah diproses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otosapp.subscriptionpackage')),
                ('payment_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otosapp.paymentproof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription User',
                'verbose_name_plural': 'Subscription User',
                'ordering': ['-end_date'],
            },
        ),
    ]
