# Generated by Django 5.1.2 on 2025-08-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0014_remove_subscriptionpackage_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Metode Pembayaran')),
                ('payment_type', models.CharField(choices=[('bank', 'Transfer Bank'), ('ewallet', 'E-Wallet'), ('other', 'Lainnya')], default='bank', max_length=10, verbose_name='Jenis Pembayaran')),
                ('account_number', models.CharField(max_length=50, verbose_name='Nomor Rekening/Akun')),
                ('account_name', models.CharField(max_length=100, verbose_name='Nama Pemilik Rekening')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metode Pembayaran',
                'verbose_name_plural': 'Metode Pembayaran',
                'ordering': ['payment_type', 'name'],
            },
        ),
    ]
