# Generated by Django 5.1.2 on 2025-08-12 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0015_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Universitas')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasi')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('minimum_utbk_score', models.IntegerField(default=400, help_text='Nilai minimum UTBK yang aman untuk masuk universitas ini (0-1000)', verbose_name='Nilai UTBK Minimum (Aman)')),
                ('tier', models.CharField(choices=[('tier1', 'Tier 1 (Top Universities)'), ('tier2', 'Tier 2 (Good Universities)'), ('tier3', 'Tier 3 (Standard Universities)')], default='tier3', max_length=20, verbose_name='Tingkatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Universitas',
                'verbose_name_plural': 'Universitas',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Catatan personal tentang target universitas', null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_targets', to='otosapp.university', verbose_name='Universitas Target Aman')),
                ('primary_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_targets', to='otosapp.university', verbose_name='Universitas Target Utama')),
                ('secondary_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_targets', to='otosapp.university', verbose_name='Universitas Target Cadangan')),
                ('user', models.OneToOneField(limit_choices_to={'role__role_name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='university_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Target Universitas Student',
                'verbose_name_plural': 'Target Universitas Student',
            },
        ),
    ]
