# Generated by Django 5.1.2 on 2025-08-12 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0016_university_universitytarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(help_text='Nama paket tryout (contoh: UTBK Saintek 2025)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Deskripsi paket tryout')),
                ('is_active', models.BooleanField(default=True, help_text='Apakah paket ini aktif dan tersedia untuk siswa')),
                ('total_time', models.IntegerField(help_text='Total waktu pengerjaan dalam menit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='tryout_package',
            field=models.ForeignKey(blank=True, help_text='Paket tryout yang digunakan (jika ada)', null=True, on_delete=django.db.models.deletion.CASCADE, to='otosapp.tryoutpackage'),
        ),
        migrations.CreateModel(
            name='TryoutPackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(help_text='Jumlah soal dari kategori ini dalam paket')),
                ('max_score', models.FloatField(help_text='Skor maksimum untuk kategori ini (kontribusi ke total 1000)')),
                ('order', models.PositiveIntegerField(default=1, help_text='Urutan kategori dalam paket')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otosapp.category')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otosapp.tryoutpackage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('package', 'category')},
            },
        ),
        migrations.AddField(
            model_name='tryoutpackage',
            name='categories',
            field=models.ManyToManyField(through='otosapp.TryoutPackageCategory', to='otosapp.category'),
        ),
    ]
