# Generated by Django 5.1.2 on 2025-08-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0017_tryoutpackage_test_tryout_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='current_question',
            field=models.IntegerField(default=1, verbose_name='Current Question Index'),
        ),
    ]
