# Generated by Django 5.1.2 on 2025-08-19 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0021_merge_category_teachers_and_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Additional teachers assigned to this category', related_name='teaching_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
