# Generated by Django 5.1.2 on 2025-08-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0022_alter_category_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Jawaban teks untuk soal isian', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.TextField(blank=True, help_text='Jawaban benar untuk soal isian (pisahkan dengan koma jika ada beberapa jawaban yang benar)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('essay', 'Isian/Essay')], default='multiple_choice', help_text='Tipe soal: pilihan ganda atau isian', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otosapp.choice'),
        ),
    ]
