# Generated by Django 5.1.2 on 2025-08-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0023_answer_text_answer_question_correct_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, null=True, upload_to='choice_images/'),
        ),
    ]
