# Generated by Django 5.1.2 on 2025-08-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0025_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Pembahasan atau penjelasan mengapa jawabannya demikian (opsional)', null=True),
        ),
    ]
