# Generated by Django 5.1.2 on 2025-09-10 07:54

import otosapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0026_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='scoring_method',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom'), ('utbk', 'UTBK')], default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=otosapp.models.get_storage, upload_to='choice_images/'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='proof_image',
            field=models.ImageField(max_length=500, storage=otosapp.models.get_storage, upload_to='payment_proofs/', verbose_name='Bukti Pembayaran'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=otosapp.models.get_storage, upload_to='profile_pictures/'),
        ),
    ]
