# Generated by Django 5.1.2 on 2025-09-11 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0027_alter_category_scoring_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Tanggal rilis subtest ini"),
        ),
        migrations.AddField(
            model_name='tryoutpackage',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Tanggal rilis paket tryout ini"),
        ),
    ]
