# Generated by Django 5.1.2 on 2025-09-22 01:46

import django.db.models.deletion
import otosapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0028_auto_20250911_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='close_requested_at',
            field=models.DateTimeField(blank=True, help_text='Waktu ketika guru meminta penutupan', null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='close_requested_by',
            field=models.ForeignKey(blank=True, help_text='Guru yang meminta penutupan thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, help_text='DEPRECATED: Use WYSIWYG editor in choice_text instead. Kept for existing data compatibility.', max_length=500, null=True, storage=otosapp.models.get_storage, upload_to='choice_images/'),
        ),
        migrations.AlterField(
            model_name='tryoutpackagecategory',
            name='max_score',
            field=models.FloatField(help_text='Skor maksimum untuk kategori ini (kontribusi ke total 7000 untuk 7 subtest)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='minimum_utbk_score',
            field=models.IntegerField(default=400, help_text='Nilai minimum UTBK yang aman untuk masuk universitas ini (0-7000)', verbose_name='Nilai UTBK Minimum (Aman)'),
        ),
        migrations.CreateModel(
            name='ThreadStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='otosapp.messagethread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
