# Generated by Django 5.1.2 on 2025-09-22 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0029_messagethread_close_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Waktu ketika thread ditutup', null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='User yang menutup thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text='Waktu ketika thread dibuka kembali', null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='reopened_by',
            field=models.ForeignKey(blank=True, help_text='User yang membuka kembali thread', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
