# Generated by Django 5.1.2 on 2025-10-09 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0030_messagethread_closed_at_messagethread_closed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('test_count', 'Jumlah Tryout'), ('avg_score', 'Rata-rata Skor'), ('total_score', 'Total Poin')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.FloatField(help_text='Nilai target yang ingin dicapai')),
                ('timeframe_start', models.DateField(blank=True, help_text='Tanggal mulai perhitungan', null=True)),
                ('timeframe_end', models.DateField(blank=True, help_text='Tanggal akhir (deadline)', null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Target Siswa',
                'verbose_name_plural': 'Target Siswa',
                'ordering': ['-created_at'],
            },
        ),
    ]
