# Generated by Django 5.1.2 on 2025-10-09 02:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0031_studentgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(help_text='Isi pengumuman yang akan ditampilkan kepada user')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Waktu pengumuman mulai ditampilkan')),
                ('duration_minutes', models.PositiveIntegerField(default=1440, help_text='Durasi tampil (menit) sebelum pengumuman hilang otomatis')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Waktu pengumuman berhenti tampil', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Nonaktifkan untuk menyembunyikan pengumuman')),
                ('students_require_active_subscription', models.BooleanField(default=False, help_text='Tampilkan hanya kepada siswa dengan langganan aktif')),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_removed', to=settings.AUTH_USER_MODEL)),
                ('target_roles', models.ManyToManyField(blank=True, help_text='Kosongkan untuk menampilkan ke semua role', related_name='broadcast_messages', to='otosapp.role')),
            ],
            options={
                'verbose_name': 'Pengumuman Broadcast',
                'verbose_name_plural': 'Pengumuman Broadcast',
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
    ]
