# Generated by Django 5.1.2 on 2025-10-15 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0035_update_access_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(choices=[('academic', 'Pertanyaan Materi'), ('technical', 'Masalah Teknis/Aplikasi'), ('report', 'Pelaporan Masalah'), ('general', 'Umum'), ('info', 'Informasi Admin')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('purpose', models.CharField(choices=[('activate', 'Account Activation')], default='activate', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='otosapp_ema_token_1ff7b9_idx'), models.Index(fields=['purpose', 'expires_at'], name='otosapp_ema_purpose_291a16_idx')],
            },
        ),
    ]
