# Generated by Django 5.1.2 on 2025-10-19 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otosapp', '0036_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackagePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_price_changes', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='otosapp.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Riwayat Harga Paket',
                'verbose_name_plural': 'Riwayat Harga Paket',
                'ordering': ['-changed_at'],
            },
        ),
    ]
